target: possion_2d
n_samps_domain: 1000000
n_samps_bc: 1000000
batch_size: 5000
shape_name: pentagon
shape_kwargs:
    vertices: [[0., .1], [1., 0.], [.9, .9], [.5, .6], [.1, .8]]
    boundary_type: 'unweighted'

